module.exports.classifyToxicity = async (req, res) => {
    const { statement } = req.body;
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${ process.env.OPENAI_API_KEY }`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        model: 'gpt-3.5-turbo',
        messages: [{ role: 'user', content: `Classify the following statement as either toxic or non-toxic - ${ statement }.
        If it is toxic, provide a corresponding statement that is non-toxic in the below format in place of value for non-toxic statement.
        If it is non-toxic, keep the value of non-toxic statement as it is.
        The statement can be a post/comment from a social media platform.
        The response generated by you must be in the json format as follows:
         {
            "class": 'toxic' // 'non-toxic' for non-toxic statement
            "non-toxic statement": value
         }
        ` }],
        max_tokens: 100,
      }),
    })
  
    const data = await response.json();
    return res.send(data.choices[0].message.content);
}